<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ForgeRecover.Cli</RootNamespace>
    <AssemblyName>forge-recover</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ForgeRecover.Core\ForgeRecover.Core.csproj" />
  </ItemGroup>
</Project>
